// File: contracts/subscription_vault/src/types/data_key/subscription.rs

use soroban_sdk::{Address, Symbol, Bytes, BytesN, String, Vec};

/// Subscription‑related storage keys grouped for readability.
#[derive(Clone, Debug)]
pub enum DataKeySubscription {
    Sub(u32),
    ChargedPeriod(u32),
    IdemKey(u32),
    EmergencyStop,
    MerchantPaused(Address),
    BillingStatement(u32, u32),
    BillingStatementsBySubscription(u32),
    BillingStatementsByMerchant(Address),
    TotalAccounted(Address),
    Recovery(String),
    MerchantConfig(Address),
    MerchantEarnings(Address, Address),
    MerchantTokens(Address),
    UsageLimits(u32),
    UsageState(u32),
    GracePeriod,
    FeeBps,
    Treasury,
    AcceptedTokens,
    TokenDecimals(Address),
    NextPlanId,
    Plan(u32),
    SubPlan(u32),
    PlanMaxActive(u32),
    CreditLimit(Address, Address),
    TokenSubs(Address),
    SubscriberSubs(Address),
    MerchantBalance(Address, Address),
    Blocklist(Address),
    Oracle,
    BillingPeriodSnapshot(u32, u64),
    BillingPeriodSnapshotIndex(u32),
    AdminNonce(Address, u32),
    Metadata(u32, String),
    MetadataKeys(u32),
    Operator,
    BillingRetentionConfig,
    BillingStatementSequence(u32),
    BillingStatementAggregate(u32),
    MerchantMaxSubs(Address),
    // Additional subscription‑specific keys can be added here.
}

impl DataKeySubscription {
    /// Returns the original discriminant for this variant.
    pub const fn canonical_discriminant(&self) -> u32 {
        match self {
            DataKeySubscription::Sub(_) => 6,
            DataKeySubscription::ChargedPeriod(_) => 7,
            DataKeySubscription::IdemKey(_) => 8,
            DataKeySubscription::EmergencyStop => 9,
            DataKeySubscription::MerchantPaused(_) => 10,
            DataKeySubscription::BillingStatement(_, _) => 11,
            DataKeySubscription::BillingStatementsBySubscription(_) => 12,
            DataKeySubscription::BillingStatementsByMerchant(_) => 13,
            DataKeySubscription::TotalAccounted(_) => 14,
            DataKeySubscription::Recovery(_) => 15,
            DataKeySubscription::MerchantConfig(_) => 16,
            DataKeySubscription::MerchantEarnings(_, _) => 17,
            DataKeySubscription::MerchantTokens(_) => 18,
            DataKeySubscription::UsageLimits(_) => 19,
            DataKeySubscription::UsageState(_) => 20,
            DataKeySubscription::GracePeriod => 21,
            DataKeySubscription::FeeBps => 22,
            DataKeySubscription::Treasury => 23,
            DataKeySubscription::AcceptedTokens => 24,
            DataKeySubscription::TokenDecimals(_) => 25,
            DataKeySubscription::NextPlanId => 26,
            DataKeySubscription::Plan(_) => 27,
            DataKeySubscription::SubPlan(_) => 28,
            DataKeySubscription::PlanMaxActive(_) => 29,
            DataKeySubscription::CreditLimit(_, _) => 30,
            DataKeySubscription::TokenSubs(_) => 31,
            DataKeySubscription::SubscriberSubs(_) => 32,
            DataKeySubscription::MerchantBalance(_, _) => 33,
            DataKeySubscription::Blocklist(_) => 34,
            DataKeySubscription::Oracle => 35,
            DataKeySubscription::BillingPeriodSnapshot(_, _) => 36,
            DataKeySubscription::BillingPeriodSnapshotIndex(_) => 37,
            DataKeySubscription::AdminNonce(_, _) => 38,
            DataKeySubscription::Metadata(_, _) => 39,
            DataKeySubscription::MetadataKeys(_) => 40,
            DataKeySubscription::Operator => 41,
            DataKeySubscription::BillingRetentionConfig => 42,
            DataKeySubscription::BillingStatementSequence(_) => 43,
            DataKeySubscription::BillingStatementAggregate(_) => 44,
            DataKeySubscription::MerchantMaxSubs(_) => 45,
        }
    }
}

// Provide conversion into the top‑level DataKey.
impl From<DataKeySubscription> for super::DataKey {
    fn from(inner: DataKeySubscription) -> Self {
        match inner {
            DataKeySubscription::Sub(v) => super::DataKey::Sub(v),
            DataKeySubscription::ChargedPeriod(v) => super::DataKey::ChargedPeriod(v),
            DataKeySubscription::IdemKey(v) => super::DataKey::IdemKey(v),
            DataKeySubscription::EmergencyStop => super::DataKey::EmergencyStop,
            DataKeySubscription::MerchantPaused(v) => super::DataKey::MerchantPaused(v),
            DataKeySubscription::BillingStatement(a, b) => super::DataKey::BillingStatement(a, b),
            DataKeySubscription::BillingStatementsBySubscription(v) => super::DataKey::BillingStatementsBySubscription(v),
            DataKeySubscription::BillingStatementsByMerchant(v) => super::DataKey::BillingStatementsByMerchant(v),
            DataKeySubscription::TotalAccounted(v) => super::DataKey::TotalAccounted(v),
            DataKeySubscription::Recovery(v) => super::DataKey::Recovery(v),
            DataKeySubscription::MerchantConfig(v) => super::DataKey::MerchantConfig(v),
            DataKeySubscription::MerchantEarnings(a, b) => super::DataKey::MerchantEarnings(a, b),
            DataKeySubscription::MerchantTokens(v) => super::DataKey::MerchantTokens(v),
            DataKeySubscription::UsageLimits(v) => super::DataKey::UsageLimits(v),
            DataKeySubscription::UsageState(v) => super::DataKey::UsageState(v),
            DataKeySubscription::GracePeriod => super::DataKey::GracePeriod,
            DataKeySubscription::FeeBps => super::DataKey::FeeBps,
            DataKeySubscription::Treasury => super::DataKey::Treasury,
            DataKeySubscription::AcceptedTokens => super::DataKey::AcceptedTokens,
            DataKeySubscription::TokenDecimals(v) => super::DataKey::TokenDecimals(v),
            DataKeySubscription::NextPlanId => super::DataKey::NextPlanId,
            DataKeySubscription::Plan(v) => super::DataKey::Plan(v),
            DataKeySubscription::SubPlan(v) => super::DataKey::SubPlan(v),
            DataKeySubscription::PlanMaxActive(v) => super::DataKey::PlanMaxActive(v),
            DataKeySubscription::CreditLimit(a, b) => super::DataKey::CreditLimit(a, b),
            DataKeySubscription::TokenSubs(v) => super::DataKey::TokenSubs(v),
            DataKeySubscription::SubscriberSubs(v) => super::DataKey::SubscriberSubs(v),
            DataKeySubscription::MerchantBalance(a, b) => super::DataKey::MerchantBalance(a, b),
            DataKeySubscription::Blocklist(v) => super::DataKey::Blocklist(v),
            DataKeySubscription::Oracle => super::DataKey::Oracle,
            DataKeySubscription::BillingPeriodSnapshot(a, b) => super::DataKey::BillingPeriodSnapshot(a, b),
            DataKeySubscription::BillingPeriodSnapshotIndex(v) => super::DataKey::BillingPeriodSnapshotIndex(v),
            DataKeySubscription::AdminNonce(a, b) => super::DataKey::AdminNonce(a, b),
            DataKeySubscription::Metadata(a, b) => super::DataKey::Metadata(a, b),
            DataKeySubscription::MetadataKeys(v) => super::DataKey::MetadataKeys(v),
            DataKeySubscription::Operator => super::DataKey::Operator,
            DataKeySubscription::BillingRetentionConfig => super::DataKey::BillingRetentionConfig,
            DataKeySubscription::BillingStatementSequence(v) => super::DataKey::BillingStatementSequence(v),
            DataKeySubscription::BillingStatementAggregate(v) => super::DataKey::BillingStatementAggregate(v),
            DataKeySubscription::MerchantMaxSubs(v) => super::DataKey::MerchantMaxSubs(v),
        }
    }
}
